### ISSUE TITLE
peer-to-peer code reviews

### ISSUE THREAD

**Issue by haftamudesta** [FevenSeyfu/Leaderboard#3]
you did a great job in implementing the requirements of the project. there are some issues we observed. so we suggest you resolve the following issues.
-the target of the function AddScore should be adding score only not clearing the form. it is better to clear the form on the event listener.
-You can use the elements property to call the elements within the formulary
-You can use the required option to validate the fields directly in Html.

**Comment by FevenSeyfu** [comment]
Thank you for your constructive feedback, Please note I have made the suggested changes.
